export interface Ingredient {
  codice: string
  prodotto: string
  pvMedio: number
  ub: string
  categoria: string
}

export const CATALOG: Ingredient[] = [
  { codice: 'ADD_FORNO_ZERO_SCUSE', prodotto: 'ADD FORNO ZERO SCUSE', pvMedio: 2.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'ADD_FRITTE_ZERO_SCUSE', prodotto: 'ADD FRITTE ZERO SCUSE', pvMedio: 2.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'ADD_ON_DRINK_1', prodotto: 'RICETTA BASE', pvMedio: 0, ub: 'pz', categoria: 'COMMENTI' },
  { codice: 'ADD_ON_DRINK_2', prodotto: '+ HENDRICK\'S', pvMedio: 2, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'ADD_ON_DRINK_3', prodotto: '#NOME?', pvMedio: 3, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'ADD_ON_DRINK_5', prodotto: 'ADD GIN AMARENA FABBRI', pvMedio: 3, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'ADD_ON_DRINK_6', prodotto: 'ADD TANQUERAY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'ADD_ON_VODKA', prodotto: 'ADD ON VODKA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'AMARI_1', prodotto: 'AVERNA', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_10', prodotto: 'LAGAVULIN', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_11', prodotto: 'OBAN', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_12', prodotto: 'TALISKER', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_13', prodotto: 'CAOL ILA', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_14', prodotto: 'ZACAPA 23Y', pvMedio: 8, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_15', prodotto: 'GRAPPA POLI CLASSICA', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_16', prodotto: 'GRAPPA BARRIQUE', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_17', prodotto: 'ST. JAMES', pvMedio: 5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_18', prodotto: 'DIPLOMATICO 12Y', pvMedio: 5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_19', prodotto: 'KRAKEN', pvMedio: 5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_2', prodotto: 'AMARO DEL CAPO', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_21', prodotto: 'DALWHINNIE 15Y', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_22', prodotto: 'GRAPPA CHARDONNAY', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_23', prodotto: 'GRAPPA POLI MOSCATO', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_24', prodotto: 'LIMONCELLO', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_25', prodotto: 'ANIMA NERA', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_26', prodotto: 'BOWMORE 12Y', pvMedio: 7, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_27', prodotto: 'MIRTO', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_28', prodotto: 'AMARO DOPPIO MALTO', pvMedio: 3.5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_3', prodotto: 'BRAULIO', pvMedio: 4.4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_30', prodotto: 'PAMPERO ANNIVERSARIO', pvMedio: 5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_31', prodotto: 'AMARO CAMATTI', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_4', prodotto: 'MONTENEGRO', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_5', prodotto: 'JAGERMEISTER', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_6', prodotto: 'RAMAZZOTTI', pvMedio: 0, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_7', prodotto: 'SAMBUCA', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_8', prodotto: 'BAILEYS', pvMedio: 4, ub: 'pz', categoria: 'AMARI' },
  { codice: 'AMARI_9', prodotto: 'JOHNNIE WALKER RED', pvMedio: 5, ub: 'pz', categoria: 'AMARI' },
  { codice: 'BABY_1', prodotto: 'COTOLETTA BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_10', prodotto: 'PIZZA NUTELLA BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_15', prodotto: 'PASTA BABY ROSSA NEW', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_16', prodotto: 'PASTA BABY BIANCA NEW', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_2', prodotto: 'BURGER BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_3', prodotto: 'FILETTO POLLO BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_7', prodotto: 'MARGHERITA BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BABY_8', prodotto: 'COPPA NUTELLA BABY', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'BEACH_BASE_1', prodotto: 'BASE RISO', pvMedio: 0, ub: 'pz', categoria: 'BAR' },
  { codice: 'BEACH_BASE_2', prodotto: 'BASE INSALATA', pvMedio: 0, ub: 'pz', categoria: 'BAR' },
  { codice: 'BEACH_SECONDI_1', prodotto: 'FRITTO CALAMARI', pvMedio: 22, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BEACH_SECONDI_2', prodotto: 'FRITTO GAMBERI E CALAMARI', pvMedio: 24, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BEER_TOUR_1', prodotto: 'SHOT ULTRA PILS', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_10', prodotto: 'SHOT + CHE ROSSA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_11', prodotto: 'SHOT IMPERIALE', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_12', prodotto: 'SHOT BLACK STOUT', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_13', prodotto: 'SHOT SUPER CHIARA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_14', prodotto: 'SHOT \'O SOLE MIO', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_15', prodotto: 'GIRO DI MALTO', pvMedio: 9, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_16', prodotto: 'GIRO DI LUPPOLI', pvMedio: 10, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_17', prodotto: 'GIRO DI AROMI', pvMedio: 10, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_18', prodotto: 'COMANDA COLORE', pvMedio: 26, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_19', prodotto: 'SHOT REGINA', pvMedio: 2.25, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_2', prodotto: 'SHOT IPER WEISS', pvMedio: 2.25, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_21', prodotto: 'SHOT WEST IPA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_22', prodotto: 'SHOT MAGNUS', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_23', prodotto: 'SHOT SUPER BLANCHE', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_24', prodotto: 'SHOT CHIARA ALCOOL FREE', pvMedio: 2.5, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_25', prodotto: 'SHOT SUMMER ALCOOL FREE', pvMedio: 2.5, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_3', prodotto: 'SHOT SUMMER IPA', pvMedio: 2.25, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_4', prodotto: 'SHOT EXTRA BITTER', pvMedio: 2.25, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_5', prodotto: 'SHOT HONEY IPA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_6', prodotto: 'SHOT ZINGI ALE', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_7', prodotto: 'SHOT BELLA ROSSA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_8', prodotto: 'SHOT COCOA IPA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_9', prodotto: 'SHOT SEXY IPA', pvMedio: 0, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BEER_TOUR_COMPONIBILE', prodotto: 'BEER TOUR COMPONIBILE', pvMedio: 9, ub: 'pz', categoria: 'BEER TOUR 🍻' },
  { codice: 'BIBITE_1', prodotto: 'ACQUA NATURALE', pvMedio: 2.5, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_10', prodotto: 'NO ACQUA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'BIBITE_13', prodotto: 'ACQUA NATURALE 0,75', pvMedio: 2, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_14', prodotto: 'ACQUA FRIZZANTE 0,75', pvMedio: 2, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_15', prodotto: 'ACQUA PANNA PET', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_16', prodotto: 'ACQUA S. PELLEGRINO PET', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_17', prodotto: 'COLA ZERO POLARA', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_17_', prodotto: 'COLA ZERO', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_18', prodotto: 'RED BULL', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_19', prodotto: 'RED BULL ZERO', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_2', prodotto: 'ACQUA FRIZZANTE', pvMedio: 2.5, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_20', prodotto: 'PANNA 0.75', pvMedio: 2, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_21', prodotto: 'COCA COLA VAP', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_22', prodotto: '0.33 COCA COLA ZERO', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_23', prodotto: '0.33 FANTA', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_24', prodotto: '0.33 SPRITE', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_25', prodotto: '0.33 FUZE TEA LEMON', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_26', prodotto: '0.33 FUZE TEA PESCA', pvMedio: 8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_27', prodotto: 'COCA COLA PET', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_28', prodotto: 'COCA COLA ZERO PET', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_29', prodotto: 'FANTA PET', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_3', prodotto: 'COLA', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_30', prodotto: 'SPRITE PET', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_31', prodotto: 'NATURALE MICROFILTRATA', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_32', prodotto: 'FRIZZANTE MICROFILTRATA', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_36', prodotto: '0.33 COCA COLA ZERO CAFFEINA ZERO ZUCCHERI', pvMedio: 4.4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_37', prodotto: 'RED BULL SUMMER EDITION', pvMedio: 3, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_4', prodotto: 'GASSOSA', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_5', prodotto: 'THE PESCA', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_6', prodotto: 'THE LIMONE', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_7', prodotto: 'TONICA', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_8', prodotto: 'LIMONATA', pvMedio: 4, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIBITE_9', prodotto: 'ARANCIATA', pvMedio: 3.8, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIRRE_MEDIE_1', prodotto: '0.4 ULTRA PILS', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_10', prodotto: '0.4 + CHE ROSSA', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_11', prodotto: '0.4 IMPERIALE', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_12', prodotto: '0.4 BLACK STOUT', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_13', prodotto: '0.4 PANACHE', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_14', prodotto: '0.4 RADLER', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_15', prodotto: '0.4 SUPER CHIARA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_16', prodotto: '0.4 \'O SOLE MIO', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_17', prodotto: '0.4 WEST IPA', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_18', prodotto: '0.4 REGINA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_19', prodotto: '0.4 MAGNUS', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_2', prodotto: '0.4 IPER WEISS', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_20', prodotto: '0.4 SUPER BLANCHE', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_21', prodotto: '0.4 CHIARA ALCOOL FREE', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_22', prodotto: '0.4 SUMMER ALCOOL FREE', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_3', prodotto: '0.4 SUMMER IPA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_4', prodotto: '0.4 EXTRA BITTER', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_5', prodotto: '0.4 HONEY IPA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_6', prodotto: '0.4 ZINGI ALE', pvMedio: 6.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_7', prodotto: '0.4 BELLA ROSSA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_8', prodotto: '0.4 COCOA IPA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_MEDIE_9', prodotto: '0.4 SEXY IPA', pvMedio: 6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_PICCOLE_1', prodotto: '0.2 ULTRA PILS', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_10', prodotto: '0.2 + CHE ROSSA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_11', prodotto: '0.2 IMPERIALE', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_12', prodotto: '0.2 BLACK STOUT', pvMedio: 3.6, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_13', prodotto: '0.2 PANACHE', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_14', prodotto: '0.2 RADLER', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_15', prodotto: '0.2 SUPER CHIARA', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_16', prodotto: '0.2 \'O SOLE MIO', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_17', prodotto: '0.2 WEST IPA', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_18', prodotto: '0.2 REGINA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_19', prodotto: '0.2 MAGNUS', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_2', prodotto: '0.2 IPER WEISS', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_20', prodotto: '0.2 SUPER BLANCHE', pvMedio: 0, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_21', prodotto: '0.2 CHIARA ALCOOL FREE', pvMedio: 4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_22', prodotto: '0.2 SUMMER ALCOOL FREE', pvMedio: 3.8, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_3', prodotto: '0.2 SUMMER IPA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_4', prodotto: '0.2 EXTRA BITTER', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_5', prodotto: '0.2 HONEY IPA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_6', prodotto: '0.2 ZINGI ALE', pvMedio: 3.6, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_7', prodotto: '0.2 BELLA ROSSA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_8', prodotto: '0.2 COCOA IPA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PICCOLE_9', prodotto: '0.2 SEXY IPA', pvMedio: 3.4, ub: 'pz', categoria: 'BIRRE 0.2 🍻' },
  { codice: 'BIRRE_PLASTICA_17', prodotto: 'ACQUA NATURALE PET', pvMedio: 1.5, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIRRE_PLASTICA_18', prodotto: 'ACQUA GASSATA PET', pvMedio: 1.5, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'BIRRE_PROMO_EUROPEI', prodotto: 'BIRRE PROMO EUROPEI', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'BIRRE_STADIO_1', prodotto: 'LEFFE BLONDE', pvMedio: 10.8, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_STADIO_2', prodotto: 'LEFFE ROUGE', pvMedio: 572.4, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_STADIO_3', prodotto: 'LEFFE RITUEL', pvMedio: 291.6, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_STADIO_5', prodotto: 'HOEGAARDEN MEDIA', pvMedio: 6.8, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_STADIO_6', prodotto: 'MIDWAY GOOSE ISLAND', pvMedio: 297, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BIRRE_STADIO_7', prodotto: 'BUD', pvMedio: 6.8, ub: 'pz', categoria: 'BIRRE 0.4 🍺' },
  { codice: 'BRACE_10', prodotto: 'GALLETTO MEDITERRANEO', pvMedio: 16.8, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_11', prodotto: 'GALLETTO AL FUOCO ROSSO', pvMedio: 16.8, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_12', prodotto: 'DELIVERY BRACE MISTA 2 PX', pvMedio: 39.6, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_14', prodotto: 'POLPO ALLA GRIGLIA', pvMedio: 21.6, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_17', prodotto: 'FIORENTINA', pvMedio: 0, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_18', prodotto: 'COSTATA', pvMedio: 214.68, ub: 'pz', categoria: 'BRACE' },
  { codice: 'BRACE_2', prodotto: 'COSTINE DI MAIALE', pvMedio: 16.8, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_26', prodotto: 'BRACE CUBEROLL 1PX', pvMedio: 0, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_27', prodotto: 'TAGLIATA DI POLLO', pvMedio: 13.8, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_32', prodotto: 'GRAN TAGLIATA NEW 11/24', pvMedio: 0, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_33', prodotto: 'GRAN TAGLIATA SPECIALE NEW', pvMedio: 18.8, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_34', prodotto: 'BRACE MISTA 1PX new', pvMedio: 0, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_41', prodotto: 'INSALATA BURRATA E VERDURE ALLA BRACE', pvMedio: 12.8, ub: 'pz', categoria: 'INSALATE 🥬' },
  { codice: 'BRACE_43', prodotto: 'TAGLIATA DI POLLO BBQ', pvMedio: 11.84, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_45', prodotto: 'TRE DI POLLO', pvMedio: 12.64, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BRACE_8', prodotto: 'LA GIGANTE', pvMedio: 21.6, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'BURGER_10', prodotto: 'POLPO E BURRATA', pvMedio: 14.8, ub: 'pz', categoria: 'SMASH BURGER 🍔' },
  { codice: 'BURGER_25', prodotto: '‘NDUJA E BELLA LODI', pvMedio: 12.4, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_35', prodotto: 'PROVOLA E BACON', pvMedio: 13.4, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_36', prodotto: 'PULLED PORK ALL\'ITALIANA', pvMedio: 11.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_54', prodotto: 'POLLO FRITTO BURGER', pvMedio: 0, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_56', prodotto: 'FISH AND CHIPS', pvMedio: 10.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_60', prodotto: 'IL TROPPO BUONO', pvMedio: 0, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_72', prodotto: 'BURGER CARBONARA OLE', pvMedio: 41.4, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_76', prodotto: 'SUPER BBQ', pvMedio: 0, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_78', prodotto: 'TARTARE E BELLA LODI BURGER', pvMedio: 13.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'BURGER_81', prodotto: 'SUPER CLASSICO BEACH', pvMedio: 11.2, ub: 'pz', categoria: 'BURGER' },
  { codice: 'CAFFE_1', prodotto: 'CAFFE\'', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_10', prodotto: 'CAFFE\' LATTE', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_12', prodotto: 'MACCHIATONE', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_13', prodotto: 'CAFFE\' DOPPIO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_14', prodotto: 'CIOCCOLATA PICCOLA', pvMedio: 2.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_15', prodotto: 'CIOCCOLATA GRANDE', pvMedio: 3.6, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_16', prodotto: 'ADD PANNA MONTATA', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'CAFFE_17', prodotto: 'CAFFE\' AMERICANO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_18', prodotto: 'CAFFE\' VETRO', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_19', prodotto: 'DECA VETRO', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_2', prodotto: 'CAFFE\' MACCHIATO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_20', prodotto: 'ORZO VETRO', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_21', prodotto: 'GINSENG VETRO', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_22', prodotto: 'THE CALDO', pvMedio: 4, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_3', prodotto: 'DECAFFEINATO', pvMedio: 1.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_4', prodotto: 'CAFFE\' CORRETTO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_5', prodotto: 'CAFFE\' ORZO', pvMedio: 1.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_6', prodotto: 'CAFFE\' GINSENG', pvMedio: 1.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_7', prodotto: 'CAFFE\' AL BANCO', pvMedio: 1.2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_8', prodotto: 'CAPPUCCINO', pvMedio: 2.6, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_9', prodotto: 'LATTE MACCHIATO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFE_GOURMAND', prodotto: 'CAFFE\' GOURMAND', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'CAFFETTERIA_DIP_STADIO_1', prodotto: 'CAPPUCCINO DIP STADIO', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CAFFETTERIA_DIP_STADIO_2', prodotto: 'LATTE MACCHIATO DIP STADIO', pvMedio: 2.8, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'CARAFFE_1', prodotto: 'CARAFFA ULTRA PILS', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_10', prodotto: 'CARAFFA + CHE ROSSA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_11', prodotto: 'CARAFFA SEXY IPA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_12', prodotto: 'CARAFFA IMPERIALE', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_13', prodotto: 'CARAFFA BLACK STOUT', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_14', prodotto: 'CARAFFA \'O SOLE MIO', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_16', prodotto: 'CARAFFA REGINA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_17', prodotto: 'CARAFFA MAGNUS', pvMedio: 0, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_18', prodotto: 'CARAFFA SUPER BLANCHE', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_2', prodotto: 'CARAFFA SUPER CHIARA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_20', prodotto: 'CARAFFA CHIARA ALCOOL FREE', pvMedio: 22, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_21', prodotto: 'CARAFFA SUMMER ALCOOL FREE', pvMedio: 22, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_3', prodotto: 'CARAFFA IPER WEISS', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_4', prodotto: 'CARAFFA SUMMER IPA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_5', prodotto: 'CARAFFA EXTRA BITTER', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_6', prodotto: 'CARAFFA HONEY IPA', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_7', prodotto: 'CARAFFA BELLA ROSSA', pvMedio: 22, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_8', prodotto: 'CARAFFA ZINGI ALE', pvMedio: 21, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CARAFFE_9', prodotto: 'CARAFFA COCOA IPA', pvMedio: 0, ub: 'pz', categoria: 'CARAFFE 🍺' },
  { codice: 'CMPXXX', prodotto: 'Compensazione', pvMedio: 0, ub: 'pz', categoria: 'RICAVI' },
  { codice: 'COCKTAILS_1', prodotto: 'SPRITZ APEROL', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_10', prodotto: 'VODKA TONIC', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_11', prodotto: 'MOSCOW MULE', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_12', prodotto: 'SEX ON THE BEACH', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_13', prodotto: 'CUBA LIBRE', pvMedio: 6, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_15', prodotto: 'MOJITO', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_17', prodotto: 'WHISKY E COLA', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_18', prodotto: 'TEQUILA SALE E LIMONE', pvMedio: 3, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_19', prodotto: 'TEQUILA BUM BUM', pvMedio: 3, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_2', prodotto: 'SPRITZ CAMPARI', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_22', prodotto: 'CLOROFILLO', pvMedio: 6, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_24', prodotto: 'CASANOVA SPRITZ', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_3', prodotto: 'NEGRONI', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_35', prodotto: 'AMERICANO', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_36', prodotto: 'SPRITZ HUGO', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_4', prodotto: 'NEGRONI SBAGLIATO', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_58', prodotto: 'RIVIERA', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_61', prodotto: 'SPRITZ SPILL', pvMedio: 0, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_62', prodotto: 'VODKA E RED BULL', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_63', prodotto: 'VODKA E RED BULL SUGAR FREE', pvMedio: 5.6, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_66', prodotto: 'BITTER BULL', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_67', prodotto: 'GOLDEN SPRITZ', pvMedio: 14, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_68', prodotto: 'PALOMA', pvMedio: 90, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_7', prodotto: 'GIN LEMON', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_8', prodotto: 'GIN TONIC', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COCKTAILS_9', prodotto: 'VODKA LEMON', pvMedio: 7, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'COLAZIONE_1', prodotto: 'PASTICCERIA', pvMedio: 1.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'COLAZIONE_2', prodotto: 'SPREMUTA', pvMedio: 3.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'COLAZIONE_4', prodotto: 'BICCH. NATURALE', pvMedio: 0.5, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'COLAZIONE_5', prodotto: 'BICCH. GASSATA', pvMedio: 1, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'COMBO_BURGER_DELIVERECT_1', prodotto: 'COMBO BURGER DELIVERECT 1', pvMedio: 15.2, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COMBO_BURGER_DELIVERECT_2', prodotto: 'COMBO BURGER DELIVERECT 2', pvMedio: 15.8, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COMBO_BURGER_DELIVERECT_3', prodotto: 'COMBO BURGER DELIVERECT 3', pvMedio: 17.2, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COMBO_BURGER_DELIVERECT_4', prodotto: 'COMBO BURGER DELIVERECT 4', pvMedio: 15.2, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COMBO_GP_MONZA', prodotto: 'BIRRA GP MONZA', pvMedio: 4.4, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'CONCERTI_FOOD_1', prodotto: 'HAMBURGER E PATATINE', pvMedio: 32, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'CONCERTI_FOOD_2', prodotto: 'POLLO FRITTO E PATATINE', pvMedio: 28.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'CONCERTI_FOOD_3', prodotto: 'PULLED PORK E PATATINE', pvMedio: 16, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'CONCERTI_FOOD_4', prodotto: 'SPIEDINI POLLO E PATATINE', pvMedio: 15, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'CONTORNI_1', prodotto: 'PATATE A FIAMMIFERO', pvMedio: 4, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNI_12', prodotto: 'VERDURE GRIGLIATE', pvMedio: 4.2, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNI_13', prodotto: 'ORTO FRESCO BABY', pvMedio: 4.4, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNI_14', prodotto: 'CONTORNO CARNE', pvMedio: 0, ub: 'pz', categoria: 'BRACE' },
  { codice: 'CONTORNI_2', prodotto: 'PATATE A SPICCHIO', pvMedio: 4, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNI_6', prodotto: 'PANE SALA 1 PX', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNI_8', prodotto: 'PATATE CHIPS', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNO_CREMONINI_1', prodotto: 'PATATE A SPICCHIO CREMONINI', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNO_CREMONINI_2', prodotto: 'FIAMMIFERO CREMONINI', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'CONTORNO_CREMONINI_3', prodotto: 'CONTORNO BRACE CREMONINI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'CONTORNO_CREMONINI_4', prodotto: 'VERDURE GRILL CREMONINI', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'COPERTI_13', prodotto: 'COPERTO MANAGER', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'COPERTI_18', prodotto: 'COPERTO MENSA', pvMedio: 0, ub: 'pz', categoria: 'COPERTI_10' },
  { codice: 'COPERTI_20', prodotto: 'COPERTO BURGER CINEMA', pvMedio: 19.5, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_21', prodotto: 'COPERTO FESTE CON BEVANDE', pvMedio: 55, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_22', prodotto: 'COPERTO PIZZA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_23', prodotto: 'COPERTO BRACE', pvMedio: 33, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_25', prodotto: 'COPERTO CONVENZIONE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_26', prodotto: 'MENU\' PREZZO FISSO', pvMedio: 15, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_27', prodotto: 'COPERTO BABY FREE', pvMedio: 0, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'COPERTI_29', prodotto: 'COPERTO TRAINING FZZ', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'COPERTI_3', prodotto: 'COPERTO BABY', pvMedio: 8, ub: 'pz', categoria: 'MENU\' BABY 👶🏻' },
  { codice: 'COPERTI_31', prodotto: 'COPERTO COMEDY BURGER', pvMedio: 30, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_32', prodotto: 'COPERTO COMEDY PIZZA', pvMedio: 30, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_37', prodotto: 'COPERTO FESTE SENZA BEVANDE', pvMedio: 45, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_38', prodotto: 'CHIPS MUG', pvMedio: 0, ub: 'pz', categoria: 'CONTORNI 🥗' },
  { codice: 'COPERTI_39', prodotto: 'COPERTO INSALATA CINEMA', pvMedio: 17.5, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_40', prodotto: 'COPERTO PIZZA CINEMA', pvMedio: 18.5, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'COPERTI_8', prodotto: 'POP CORN MUG', pvMedio: 0, ub: 'pz', categoria: 'POP CORN' },
  { codice: 'CREMONINI_SOFT', prodotto: 'CREMONINI ACQUA FRIZZANTE', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'CREMONINI_SOFT_1', prodotto: 'CREMONINI ACQUA NATURALE', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'DESSERT_1', prodotto: 'BIRRAMISU\'', pvMedio: 6.4, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_2', prodotto: 'CHEESECAKE NUTELLA', pvMedio: 5.8, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_23', prodotto: 'COPPA FIORDILATTE E NUTELLA', pvMedio: 6.4, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_28', prodotto: 'DESSERT GOURMAND', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_36', prodotto: 'TORTA CAPRESE NEW 11/24', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_39', prodotto: 'CHEESECAKE FRUTTI DI BOSCO', pvMedio: 12, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_41', prodotto: 'CANNOLO SCOMPOSTO', pvMedio: 5.6, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_42', prodotto: 'GNOCCO FRITTO E NUTELLA', pvMedio: 5.2, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_43', prodotto: 'CANNOLO SINGOLO', pvMedio: 3.2, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_44', prodotto: 'GOURMAND - FRUTTI DI BOSCO', pvMedio: 6.6, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_9', prodotto: 'MINI CANNOLI', pvMedio: 9, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'DESSERT_CREMONINI', prodotto: 'MACEDONIA CREMONINI', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'EVENTI_10', prodotto: 'CROISSANT PISTACCHIO', pvMedio: 2, ub: 'pz', categoria: 'COLAZIONI SAN SIRO PUB' },
  { codice: 'EVENTI_11', prodotto: 'CROISSANT VEGANO', pvMedio: 2.2, ub: 'pz', categoria: 'DESSERT' },
  { codice: 'EVENTI_12', prodotto: 'CROISSANT RIBES E MELOGRANO', pvMedio: 2.5, ub: 'pz', categoria: 'DESSERT' },
  { codice: 'EVENTI_13', prodotto: 'PAIN AU CHICOLAT', pvMedio: 4.4, ub: 'pz', categoria: 'CAFFETTERIA' },
  { codice: 'EVENTI_14', prodotto: 'CROISSANT CRUDO', pvMedio: 4.5, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'EVENTI_15', prodotto: 'CROISSANT COTTO', pvMedio: 7.2, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_16', prodotto: 'TOAST', pvMedio: 5, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_17', prodotto: 'CIABATTA COTTO E MOZZARELLA', pvMedio: 15, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_18', prodotto: 'CIABATTA VEGETARIANA', pvMedio: 35, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_19', prodotto: 'CIABATTA SALMONE E ZUCCHINE', pvMedio: 5.6, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_2', prodotto: 'CROISSANT VUOTO', pvMedio: 2, ub: 'pz', categoria: 'COLAZIONI SAN SIRO PUB' },
  { codice: 'EVENTI_20', prodotto: 'FOCACCIA CRUDO E MOZZARELLA', pvMedio: 17, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_21', prodotto: 'FOCACCIA TONNO E POMODORO', pvMedio: 8, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_22', prodotto: 'FOCACCIA MORTADELLA', pvMedio: 8, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_24', prodotto: 'POKE GAMBERI E SALMONE', pvMedio: 12, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_25', prodotto: 'POKE VEGETARIANA', pvMedio: 12, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_26', prodotto: 'POKE TONNO E MOZZARELLA', pvMedio: 12, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_27', prodotto: 'CROISSANT ALBICOCCA SC GELO', pvMedio: 4.4, ub: 'pz', categoria: 'CAFFETTERIA' },
  { codice: 'EVENTI_28', prodotto: 'CROISSANT CIOCCOLATO SC GELO', pvMedio: 2.5, ub: 'pz', categoria: 'CAFFETTERIA' },
  { codice: 'EVENTI_29', prodotto: 'CROISSANT CREMA SC GELO', pvMedio: 4.4, ub: 'pz', categoria: 'CAFFETTERIA' },
  { codice: 'EVENTI_3', prodotto: 'CROISSANT CIOCK', pvMedio: 4, ub: 'pz', categoria: 'COLAZIONI SAN SIRO PUB' },
  { codice: 'EVENTI_30', prodotto: 'CROISSANT VUOTO SC GELO', pvMedio: 4, ub: 'pz', categoria: 'BAR' },
  { codice: 'EVENTI_31', prodotto: 'BIRRAMISU DMB', pvMedio: 6.8, ub: 'pz', categoria: 'DESSERT' },
  { codice: 'EVENTI_4', prodotto: 'CROISSANT ALBICOCCA', pvMedio: 2, ub: 'pz', categoria: 'COLAZIONI SAN SIRO PUB' },
  { codice: 'EVENTI_5', prodotto: 'CROISSANT CREMA', pvMedio: 2, ub: 'pz', categoria: 'COLAZIONI SAN SIRO PUB' },
  { codice: 'FOOD_STADIO_1', prodotto: 'LASAGNA TEGLIA', pvMedio: 700, ub: 'pz', categoria: 'PASTE' },
  { codice: 'FOOD_STADIO_2', prodotto: 'KINDER BUENO', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'FOOD_STADIO_3', prodotto: 'KINDER DUPLO', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'FRUTTA_STADIO', prodotto: 'BANANA', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'FRUTTA_STADIO_1', prodotto: 'MELA', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'FRUTTA_STADIO_3', prodotto: 'PESCA', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'FRUTTA_STADIO_4', prodotto: 'PERA', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'GELATI_1', prodotto: 'CONO FIORDILATTE', pvMedio: 0, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_10', prodotto: 'PIRULO COLA', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_11', prodotto: 'MAXIBON POPS', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_12', prodotto: 'MAXIBON CLASSICO', pvMedio: 8, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_13', prodotto: 'NUI CARAMELLO SALATO', pvMedio: 12, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_14', prodotto: 'CORNETTO NO GLUTINE NO LATTOSIO', pvMedio: 12, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_15', prodotto: 'LIQUI', pvMedio: 16, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_16', prodotto: 'GHIACCIOLO (4 GUSTI)', pvMedio: 0, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_17', prodotto: 'FRAGOLINO', pvMedio: 2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_18', prodotto: 'LIPPERLI\'', pvMedio: 2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_19', prodotto: 'LONG JOHN COLA', pvMedio: 4.4, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_2', prodotto: 'CONO CIOCK', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_20', prodotto: 'LONG JOHN ARANCIA-LIMONE', pvMedio: 2.2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_21', prodotto: 'STECCO UNICORNO', pvMedio: 1.5, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_22', prodotto: 'SORBELLO', pvMedio: 2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_23', prodotto: 'GRANULATO', pvMedio: 1.6, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_24', prodotto: 'STECCO POKEMON', pvMedio: 2.2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_25', prodotto: 'GRUVI MANGO RAMINGO', pvMedio: 2.24, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_26', prodotto: 'GRUVI PISTACCHIO SINCERO', pvMedio: 2.8, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_27', prodotto: 'GRUVI MIRTILLO INASPETTATO', pvMedio: 2.8, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_28', prodotto: 'GRUVI NOCE PECAN AVVINCENTE', pvMedio: 2.8, ub: 'pz', categoria: 'BAR' },
  { codice: 'GELATI_29', prodotto: 'GELATO MERENDA PLASMON', pvMedio: 2.4, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_3', prodotto: 'CONO MISTO', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_30', prodotto: 'INTRIGO BIANCO', pvMedio: 6, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_31', prodotto: 'COPPA D\'ORO AMARENA FABBRI', pvMedio: 2, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_32', prodotto: 'COPPA D\'ORO CAFFE\' SEGAFREDO', pvMedio: 2, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_33', prodotto: 'CINQUE STELLE PANNA', pvMedio: 2.6, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_34', prodotto: 'CONO MALLOW', pvMedio: 2.8, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_35', prodotto: 'CINQUE STELLE CROCCANTINO', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_36', prodotto: 'CINQUE STELLE PANNA AMARENA', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_37', prodotto: 'CINQUE STELLE PANNA E CAFFE\'', pvMedio: 12, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_38', prodotto: 'DUETTO', pvMedio: 2.8, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_39', prodotto: 'BISCOTTO AMANDO FRUTTI DI BOSCO', pvMedio: 2.8, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_4', prodotto: 'COPPETTA FIORDILATTE', pvMedio: 0, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_40', prodotto: 'SANSONI', pvMedio: 3, ub: 'pz', categoria: 'SOFT DRINK' },
  { codice: 'GELATI_41', prodotto: 'TANDEM', pvMedio: 3, ub: 'pz', categoria: 'BAR' },
  { codice: 'GELATI_5', prodotto: 'COPPETTA CIOCK', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_6', prodotto: 'COPPETTA MISTA', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_7', prodotto: 'MACEDONIA E GELATO', pvMedio: 5, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_8', prodotto: 'ICE TOUR', pvMedio: 6, ub: 'pz', categoria: 'GELATI' },
  { codice: 'GELATI_9', prodotto: 'EXTREME PANNA', pvMedio: 3, ub: 'pz', categoria: 'GELATI' },
  { codice: 'INSALATE_10', prodotto: 'INS. POLLO FRITTO E POMODORO', pvMedio: 10.8, ub: 'pz', categoria: 'INSALATE 🥬' },
  { codice: 'INSALATE_14', prodotto: 'INSALATA TONNO', pvMedio: 12, ub: 'pz', categoria: 'INSALATE' },
  { codice: 'INSALATE_15', prodotto: 'INSALATA TAGLIATA DI POLLO E POMODORI', pvMedio: 10.8, ub: 'pz', categoria: 'INSALATE 🥬' },
  { codice: 'INSALATE_20', prodotto: 'ORTO FRESCO INSALATA', pvMedio: 6.4, ub: 'pz', categoria: 'INSALATE 🥬' },
  { codice: 'INSALATE_7', prodotto: 'MANZO E BURRATA', pvMedio: 12.8, ub: 'pz', categoria: 'INSALATE 🥬' },
  { codice: 'loyalty_discount', prodotto: 'Qodeup Discount', pvMedio: -3.4, ub: 'pz', categoria: 'SMAIL LOYALTY' },
  { codice: 'MENU\'_UEFA', prodotto: 'MENU\' UEFA', pvMedio: 684, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_10_E_LODE', prodotto: 'MENU\'', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_ASD_ALGHERO', prodotto: 'MENU\' ASD BASKET DM ALGHERO', pvMedio: 15, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_BABY_FESTE', prodotto: 'MENU\' BABY FESTE', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'MENU_BAND', prodotto: 'MENU\' BAND', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_CINEMA', prodotto: 'MENU\' CINEMA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_COMEDY_BURGER', prodotto: 'MENU\' COMEDY BURGER', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_COMEDY_DRINK', prodotto: 'MENU\' COMEDY DRINK', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_COMEDY_PIZZA', prodotto: 'MENU\' COMEDY PIZZA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_DEGUSTAZIONE', prodotto: 'MENU DEGUSTAZIONE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_DIPENDENTI', prodotto: 'MENU\' DIPENDENTI', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'MENU_DIPENDENTI_CATANIA', prodotto: 'MENU DIPENDENTI CATANIA', pvMedio: 39.6, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_DM_TRENTO', prodotto: 'MENU\' DM TRENTO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_EVENTO_IMOLA', prodotto: 'MENU EVENTO IMOLA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_EVENTO_MADONNA', prodotto: 'MENU\' EVENTO MADONNA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_FESTE_ADD_ON_DESSERT', prodotto: 'MENU\' FESTE ADD ON DESSERT', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_FESTE_CON_BEVANDE', prodotto: 'MENU FESTE CON BEVANDE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_FESTE_SENZA_BEVANDE', prodotto: 'MENU FESTE SENZA BEVANDE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_GRUPPI', prodotto: 'MENU GRUPPI', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_GRUPPI_ADD_ON_DESSERT', prodotto: 'MENU GRUPPI - ADD ON DESSERT', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'MENU_GRUPPI_BRACE', prodotto: 'MENU GRUPPI BRACE', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'MENU_GRUPPI_FRITTO_MENU\'', prodotto: 'FRITTO MENU\'', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_GRUPPI_PIZZA', prodotto: 'MENU GRUPPI - PIZZA', pvMedio: 0, ub: 'pz', categoria: 'MENU DIPENDENTI FOOD' },
  { codice: 'MENU_GRUPPI_VERONA', prodotto: 'MENU\' GRUPPI VERONA', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_LEONARDO_GENOVA', prodotto: 'MENU LEONARDO GENOVA', pvMedio: 47.5, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_11_2025', prodotto: 'MENU PRANZO 11/2025', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_CAGLIARI', prodotto: 'MENU\' PRANZO CAGLIARI', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_CAMPIGLIO', prodotto: 'MENU\' PRANZO CAMPIGLIO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_COMO', prodotto: 'MENU\' PRANZO COMO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_COMPANY', prodotto: 'MENU PRANZO COMPANY', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_SALERNO', prodotto: 'MENU\' PRANZO SALERNO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_PRANZO_TUTTO_COMPRESO', prodotto: 'MENU PRANZO TUTTO COMPRESO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MENU_TAKE._AWAY_1', prodotto: 'MENU TAKE AWAY', pvMedio: 9, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'MENU_VEGETARIANO', prodotto: 'MENU\' VEGETARIANO', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'MERCHANDISING_37', prodotto: 'CAPPELLINO DM', pvMedio: 15, ub: 'pz', categoria: 'MERCHANDISING 👕' },
  { codice: 'MINI_DESSERT', prodotto: 'MINI BIRRAMISU', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MINI_DESSERT_1', prodotto: 'MINI CHEESECAKE', pvMedio: 0, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MINI_DESSERT_2', prodotto: 'MINI CHEESECAKE NUTELLA', pvMedio: 3, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MINI_DESSERT_3', prodotto: 'MINI CANNOLO SCOMPOSTO', pvMedio: 2.4, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MINI_DESSERT_4', prodotto: 'MINI COPPA GELATO NUTELLA', pvMedio: 2.4, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MINI_DESSERT_5', prodotto: 'MINI COPPA GELATO FRUTTI DI BOSCO', pvMedio: 3, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'MSG0', prodotto: 'Aspettare', pvMedio: 0, ub: 'pz', categoria: 'COMMENTI' },
  { codice: 'PASTE_10', prodotto: 'TAGLIATELLE AL RAGU’', pvMedio: 12.4, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_10', prodotto: 'TAGLIATELLE AL RAGU’1', pvMedio: 12.4, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_20', prodotto: 'LASAGNA PORZIONE', pvMedio: 18.8, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_23', prodotto: 'TAGLIATELLA CARBONARA', pvMedio: 13.9, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_24', prodotto: 'TAGLIATELLA AMATRICIANA', pvMedio: 12.4, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_26', prodotto: 'LASAGNA BOLOGNESE', pvMedio: 13.9, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_27', prodotto: 'LASAGNA FAGIOLINI E PESTO', pvMedio: 25.8, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_28', prodotto: 'TAGLIATELLE POLPO E OLIVE', pvMedio: 63.6, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_29', prodotto: 'GNOCCHI E GRATINATI BELLA LODI', pvMedio: 9.8, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_30', prodotto: 'FUSILLI PESTO ROSSO', pvMedio: 9.8, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_31', prodotto: 'FUSILLI POMODORO BURRATA', pvMedio: 28, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_32', prodotto: 'LINGUINE VONGOLE E BOTTARGA', pvMedio: 79.2, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PASTE_33', prodotto: 'LINGUINE AL POLPO', pvMedio: 90, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PIZZE_1', prodotto: 'MARGH. BELLA LODI', pvMedio: 8.8, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_10', prodotto: 'MARGHERITA', pvMedio: 8.8, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_2', prodotto: 'CRUDO E PICCADILLY', pvMedio: 12.8, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_20', prodotto: 'MORTADELLA E BELLA LODI', pvMedio: 0, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_22', prodotto: 'CALZONE COTTO E MOZZARELLA', pvMedio: 12, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_23', prodotto: 'CALZONE MARGHERITA', pvMedio: 6, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_24', prodotto: 'PIZZA ORTOLANA', pvMedio: 0, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_25', prodotto: 'BURRATA E OLIVE', pvMedio: 13.6, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PIZZE_4', prodotto: 'BURRATA E \'NDUJA', pvMedio: 12.8, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'PRIMI_CREMONINI_1', prodotto: 'FUSILLI BURRATA E \'NDUJA', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_10', prodotto: 'CREMONINI TAGLIATELLE AL RAGU', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_2', prodotto: 'FUSILLI ALLA PARMIGIANA', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_3', prodotto: 'TAGLIATELLE PERCORINO E MENTA', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_4', prodotto: 'TAGLIATELLE \'NDUJA E MELANZANE', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_5', prodotto: 'TAGLIATELLE PICADILLY E RASPADURA', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_6', prodotto: 'TAGLIATELLE CREMA DI ZUCCHINE E RASPADURA', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_7', prodotto: 'TAGLIATELLE AL LIMONE', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_8', prodotto: 'GNOCCHI AL POMODORO', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PRIMI_CREMONINI_9', prodotto: 'GNOCCHI AL RAGU', pvMedio: 0, ub: 'pz', categoria: 'PASTE' },
  { codice: 'PROMO_BEACH_1', prodotto: '1 OMBRELLONE - 2 LETTINI PRIMA FILA', pvMedio: 30, ub: 'pz', categoria: 'NOLEGGIO OMBRELLONI' },
  { codice: 'PROMO_BEACH_2', prodotto: '1 OMBRELLONE - 2 LETTINI STANDARD', pvMedio: 20, ub: 'pz', categoria: 'NOLEGGIO OMBRELLONI' },
  { codice: 'PROMO_BEACH_3', prodotto: 'INTEGRAZIONE TERZO LETTINO', pvMedio: 10, ub: 'pz', categoria: 'NOLEGGIO OMBRELLONI' },
  { codice: 'PROMO_BEACH_6', prodotto: '1 OMBRELLONE - 2 LETTINI MATTINA', pvMedio: 20, ub: 'pz', categoria: 'NOLEGGIO OMBRELLONI' },
  { codice: 'PROMO_BEACH_7', prodotto: '1 OMBRELLONE - 2 LETTINI POMERIGGIO', pvMedio: 20, ub: 'pz', categoria: 'NOLEGGIO OMBRELLONI' },
  { codice: 'SCELTA_ACQUA_STADIO', prodotto: 'ACQUA DIP STADIO', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'SCELTA_BEVANDE_MENU_FESTE', prodotto: 'SCELTA BEVANDE MENU FESTE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'SCELTA_POKE _INSALATA', prodotto: 'SCELTA POKE INSALATA', pvMedio: 0, ub: 'pz', categoria: 'CAFFETTERIA' },
  { codice: 'SCELTA_SECONDO_DRINK_FESTE', prodotto: 'SCELTA SECONDO DRINK FESTE', pvMedio: 0, ub: 'pz', categoria: 'MENU\'' },
  { codice: 'SECONDI_CREMONINI_7', prodotto: 'MERLUZZO PANATO', pvMedio: 0, ub: 'pz', categoria: 'STARTER' },
  { codice: 'SMASH_1', prodotto: 'DOPPIO SMASH BACON E CHEDDAR', pvMedio: 14.9, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'SMASH_2', prodotto: 'TRIPLO SMASH BACON E CHEDDAR', pvMedio: 17.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'SMASH_3', prodotto: 'DOPPIO SMASH PECORINO E POMODORO', pvMedio: 14.8, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'SMASH_4', prodotto: 'TRIPLO SMASH PECORINO E POMODORO', pvMedio: 18.4, ub: 'pz', categoria: 'BURGER 🍔' },
  { codice: 'STARTER_2', prodotto: 'ANELLI DI CIPOLLA', pvMedio: 5.8, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_3', prodotto: 'RONDELLE DI MELANZANA', pvMedio: 4.8, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_33', prodotto: 'ARROSTICINI ABRUZZESI', pvMedio: 9.69, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_4', prodotto: 'GNOCCO FRITTO', pvMedio: 7.6, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_43', prodotto: 'ANTIPASTO TRICOLORE', pvMedio: 15.2, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_44', prodotto: 'SPICCHI DI FOCACCIA', pvMedio: 6.4, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_46', prodotto: 'MOZZARELLE IN CARROZZA', pvMedio: 0, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_50', prodotto: 'CHIPS BELLA LODI', pvMedio: 5, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_53', prodotto: 'CAPRESE DI BURRATA E POMODORI', pvMedio: 8.2, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_55', prodotto: 'TAGLIATA DI POLLO PANATO', pvMedio: 7.2, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_61', prodotto: 'SPIEDINI DI POLLO PANATI', pvMedio: 13.4, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_62', prodotto: 'SIAMO FRITTI', pvMedio: 13.6, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_63', prodotto: 'ARANCINI (4 PZ)', pvMedio: 6.8, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_64', prodotto: 'TARTARE PISTACCHIO E BELLA LODI', pvMedio: 15.6, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_65', prodotto: 'CAZZILLI (6PZ)', pvMedio: 10.88, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_66', prodotto: 'PROSCIUTTO E MELONE', pvMedio: 12, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STARTER_67', prodotto: 'TAGLIERE SAN DANIELE', pvMedio: 36, ub: 'pz', categoria: 'STARTER' },
  { codice: 'STRANE COPPIE_1', prodotto: 'CAPADOLCE', pvMedio: 3.5, ub: 'pz', categoria: 'STRANE COPPIE' },
  { codice: 'STRANE COPPIE_4', prodotto: 'IRLANDESE', pvMedio: 3.5, ub: 'pz', categoria: 'STRANE COPPIE' },
  { codice: 'STRANE COPPIE_5', prodotto: 'CAFFE\' IMPERIALE', pvMedio: 3.5, ub: 'pz', categoria: 'STRANE COPPIE' },
  { codice: 'SUCCHI_1', prodotto: 'SUCCO', pvMedio: 8.4, ub: 'pz', categoria: 'BIBITE' },
  { codice: 'TRANCIO_1', prodotto: 'BASE SLICE MARGHERITA', pvMedio: 15.2, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'TRANCIO_5', prodotto: 'TRANCIO FOCACCIA BIANCA', pvMedio: 2.5, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'TRANCIO_6', prodotto: 'TRANCIO FOCACCIA BIANCA DIP', pvMedio: 1.5, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'TRANCIO_7', prodotto: 'FOCACCIA CRUDO E PROVOLA', pvMedio: 6, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'TRANCIO_8', prodotto: 'FOCACCIA POMODORO E PROVOLA', pvMedio: 6, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'TRANCIO_9', prodotto: 'BASE SLICE ROSSA', pvMedio: 0, ub: 'pz', categoria: 'PIZZE' },
  { codice: 'VARIANTI BEVERAGE_10', prodotto: 'POCA SCHIUMA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_11', prodotto: 'SENZA SCHIUMA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_12', prodotto: 'TEMPERATURA AMBIENTE', pvMedio: 0, ub: 'pz', categoria: 'BIBITE 🥤' },
  { codice: 'VARIANTI BEVERAGE_13', prodotto: 'ADD GHIACCIO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_2', prodotto: 'NO GHIACCIO', pvMedio: 0, ub: 'pz', categoria: 'COCKTAILS 🍸' },
  { codice: 'VARIANTI BEVERAGE_3', prodotto: 'ADD LIMONE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_4', prodotto: 'ADD LIME', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_5', prodotto: 'ADD ARANCIA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_6', prodotto: 'ADD 1 BICCHIERE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_7', prodotto: 'ADD 2 BICCHIERI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI BEVERAGE_9', prodotto: 'ADD 4 BICCHIERI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI BEVERAGE' },
  { codice: 'VARIANTI CAFFE\'_1', prodotto: 'LUNGO', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'VARIANTI CAFFE\'_11', prodotto: 'ADD CACAO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_12', prodotto: 'ADD LATTE A PARTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_2', prodotto: 'RISTRETTO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_3', prodotto: 'ADD MACCHIATO CALDO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_4', prodotto: 'ADD MACCHIATO FREDDO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_5', prodotto: 'TAZZA GRANDE', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'VARIANTI CAFFE\'_6', prodotto: 'TAZZA PICCOLA', pvMedio: 0, ub: 'pz', categoria: 'CAFFE\' ☕' },
  { codice: 'VARIANTI CAFFE\'_7', prodotto: 'ADD SAMBUCA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_8', prodotto: 'ADD GRAPPA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CAFFE\'_9', prodotto: 'ADD BAILEYS', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CAFFE\'' },
  { codice: 'VARIANTI CONTORNI_1', prodotto: 'NO FRITTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'VARIANTI CONTORNI_10', prodotto: 'ADD PANE SALA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI CONTORNI_11', prodotto: 'NO PANE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI CONTORNI_14', prodotto: 'NO CHIPS', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'VARIANTI CONTORNI_15', prodotto: 'ADD CHIPS', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'VARIANTI CONTORNI_16', prodotto: 'ADD VERDURE GRIGLIATE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI CONTORNI_2', prodotto: 'NO SPICCHIO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI CONTORNI_4', prodotto: 'ADD FRITTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI CONTORNI_5', prodotto: 'ADD SPICCHIO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI CONTORNI_7', prodotto: 'ADD ORTO FRESCO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'VARIANTI_ FOOD_-_1', prodotto: 'NO PATTY MANZO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_10', prodotto: 'NO GRATTUGIATO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_11', prodotto: 'NO CRUDO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_14', prodotto: 'NO PEPE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_15', prodotto: 'NO OLIVE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_17', prodotto: 'NO SALSA DI POMODORO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_19', prodotto: 'NO RUCOLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_2', prodotto: 'NO COTOLETTA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_20', prodotto: 'NO CAVOLO ROSSO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_21', prodotto: 'NO POMO PICCADILLY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_27', prodotto: 'NO CIPOLLA FRESCA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_28', prodotto: 'NO CETRIOLO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_29', prodotto: 'NO \'NDUJA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_30', prodotto: 'NO CROSTINI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_32', prodotto: 'NO INSALATA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_35', prodotto: 'NO MELANZANE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_36', prodotto: 'NO ZUCCHINE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_38', prodotto: 'NO BASILICO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_4', prodotto: 'NO PANCETTA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_45', prodotto: 'NO STRACCIATELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_47', prodotto: 'NO COSTINE 350 GR', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_48', prodotto: 'NO CONTROFILETTO 100 GR', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_49', prodotto: 'NO POMO RAMATO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_5', prodotto: 'NO MOZZARELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_50', prodotto: 'NO FINOCCHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_51', prodotto: 'NO INS. GENTILE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_52', prodotto: 'NO CAROTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_56', prodotto: 'NO BURGER NO MEAT', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_57', prodotto: 'NO NUTELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_6', prodotto: 'NO BURRATA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_62', prodotto: 'NO FUNGHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_7', prodotto: 'NO RASPADURA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_8', prodotto: 'NO PECORINO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_-_9', prodotto: 'NO PROVOLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ FOOD_+_1', prodotto: 'ADD EXTRA PATTY MANZO', pvMedio: 3.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_10', prodotto: 'ADD GRATTUGIATO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_11', prodotto: 'ADD CRUDO', pvMedio: 1.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_14', prodotto: 'ADD PEPE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_15', prodotto: 'ADD OLIVE', pvMedio: 0.45, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_17', prodotto: 'ADD SALSA DI POMODORO', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_19', prodotto: 'ADD RUCOLA', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_2', prodotto: 'ADD EXTRA COTOLETTA 1 PZ', pvMedio: 3.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_20', prodotto: 'ADD CAVOLO ROSSO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_21', prodotto: 'ADD POMO PICCADILLY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_22', prodotto: 'ADD POMO GIALLI', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_27', prodotto: 'ADD CIPOLLA FRESCA', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_28', prodotto: 'ADD CETRIOLI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_29', prodotto: 'ADD \'NDUJA', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_30', prodotto: 'ADD CROSTINI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_31', prodotto: 'ADD INSALATA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_34', prodotto: 'ADD MELANZANE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_35', prodotto: 'ADD ZUCCHINE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_37', prodotto: 'ADD BASILICO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_4', prodotto: 'ADD EXTRA PANCETTA', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_40', prodotto: 'ADD STRACCIATELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_46', prodotto: 'ADD EXTRA CONTROFILETTO 100 GR', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_5', prodotto: 'ADD MOZZARELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_50', prodotto: 'ADD EXTRA SALAMELLA 1 PZ', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_51', prodotto: 'ADD COSTINE 175GR', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_52', prodotto: 'ADD COSCE DI POLLO 1 PZ', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_54', prodotto: 'ADD POMO RAMATO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_55', prodotto: 'ADD FINOCCHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_56', prodotto: 'ADD INS. GENTILE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_57', prodotto: 'ADD CAROTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_6', prodotto: 'ADD BURRATA', pvMedio: 2, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_60', prodotto: 'ADD EXTRA POLPO 1 PZ', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_62', prodotto: 'ADD EXTRA BURGER NO MEAT', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_63', prodotto: 'ADD NUTELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_67', prodotto: 'ADD FUNGHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_7', prodotto: 'ADD RASPADURA', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_8', prodotto: 'ADD PECORINO', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ FOOD_+_9', prodotto: 'ADD PROVOLA', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ SALSE_-_1', prodotto: 'NO MAYO BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_18', prodotto: 'NO SALSA CARBONARA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_19', prodotto: 'NO EMULSIONE AL PESTO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_2', prodotto: 'NO MAYO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_22', prodotto: 'NO BBQ ALLA BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ SALSE_-_23', prodotto: 'NO SALSA ALLA BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_24', prodotto: 'NO SALSA ALLE ERBE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ SALSE_-_25', prodotto: 'NO SALSA AL PEPERONCINO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_26', prodotto: 'NO SALSA BBQ BIANCA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_27', prodotto: 'NO MARMELLATA BACON E CIPOLLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ SALSE_-_28', prodotto: 'NO SEXY SAUCE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_ SALSE_-_4', prodotto: 'NO MAYO POMODORI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_5', prodotto: 'NO CREMA DI GRANA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_-_7', prodotto: 'NO EMULSIONE BASILICO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_ SALSE_+_1', prodotto: 'ADD MAYO BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_18', prodotto: 'ADD SALSA CARBONARA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_19', prodotto: 'ADD EMULSIONE AL PESTO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_2', prodotto: 'ADD MAYO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_22', prodotto: 'ADD BBQ ALLA BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_23', prodotto: 'ADD SALSA ALLA BIRRA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_24', prodotto: 'ADD SALSA ALLE ERBE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_25', prodotto: 'ADD SALSA AL PEPERONCINO', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_26', prodotto: 'ADD SALSA BBQ BIANCA', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_27', prodotto: 'ADD MARMELLATA BACON E CIPOLLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ SALSE_+_28', prodotto: 'ADD SEXY SAUCE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ SALSE_+_4', prodotto: 'ADD MAYO POMODORI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_ SALSE_+_5', prodotto: 'ADD CREMA DI GRANA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_ SALSE_+_7', prodotto: 'ADD EMULSIONE BASILICO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_FOO_-_109', prodotto: 'NO BACON A FETTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_40', prodotto: 'NO PROV. DOLCE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_50', prodotto: 'NO FUNGHI MISTI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_52', prodotto: 'NO PATTY TARTARE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_53', prodotto: 'NO CREMA PISTACCHIO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_56', prodotto: 'NO GRANA CROCCANTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_57', prodotto: 'NO POMO GIALLO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_62', prodotto: 'NO FUNGO (60 GR)', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_63', prodotto: 'NO DADOLATA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_65', prodotto: 'NO PROVOLA DOLCE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_66', prodotto: 'NO PANNA SPRAY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_67', prodotto: 'NO GUTTIAU', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_68', prodotto: 'NO CRUMBLE SBRISOLONA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_69', prodotto: 'NO SCAGLIETTE CIOCK', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_70', prodotto: 'NO MELANZANE GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_71', prodotto: 'NO CAROTE GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_72', prodotto: 'NO FINOCCHI GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_73', prodotto: 'NO CIPOLLA GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_74', prodotto: 'NO POMODORO GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_75', prodotto: 'NO ZUCCHINE GRILL', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_76', prodotto: 'NO MORTADELLA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_77', prodotto: 'NO ZUCCHINE CHIPS', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_80', prodotto: 'NO FRUTTI DI BOSCO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_81', prodotto: 'NO FAGIOLINI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_82', prodotto: 'NO FINOCCHI JULIENNE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_83', prodotto: 'NO CAROTE JULIENNE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_84', prodotto: 'NO UOVO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_-_85', prodotto: 'NO MOZZARELLA FILONE (100 GR)', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_FOOD_+_100', prodotto: 'ADD ZUCCHINE CHIPS', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_101', prodotto: 'ADD FRUTTI DI BOSCO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_102', prodotto: 'ADD FAGIOLINI', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI CONTORNI' },
  { codice: 'VARIANTI_FOOD_+_103', prodotto: 'ADD FINOCCHI JULIENNE', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_104', prodotto: 'ADD CAROTE JULIENNE', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_105', prodotto: 'ADD UOVO', pvMedio: 2, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_106', prodotto: 'ADD MOZZARELLA FILONE (100 GR)', pvMedio: 2, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_107', prodotto: 'ADD ANELLI DI CIPOLLA (6PZ)', pvMedio: 6.4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_108', prodotto: 'ADD BUN BABY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_109', prodotto: 'ADD BACON A FETTE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_110', prodotto: 'EXTRA PATTY SMASH', pvMedio: 4.4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_111', prodotto: 'NO 125 GR SOVRACOSCIA ADD COSCE 1 PZ', pvMedio: 0, ub: 'pz', categoria: 'BRACE 🔥 🥩' },
  { codice: 'VARIANTI_FOOD_+_112', prodotto: 'ADD PETTO DI POLLO (120G)', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_113', prodotto: 'ADD CREMA CIOCCOLATO 50G', pvMedio: 2, ub: 'pz', categoria: 'DESSERT 🍰' },
  { codice: 'VARIANTI_FOOD_+_114', prodotto: 'ADD GELATO CREMA (60GR)', pvMedio: 2, ub: 'pz', categoria: 'CAFFE\'' },
  { codice: 'VARIANTI_FOOD_+_39', prodotto: 'ADD EXTRA PROV. DOLCE', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_66', prodotto: 'ADD FUNGHI MISTI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_67', prodotto: 'ADD FUNGO (60 GR)', pvMedio: 2, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_68', prodotto: 'ADD DADOLATA 40G', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_70', prodotto: 'ADD PROVOLA DOLCE', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_71', prodotto: 'ADD PANNA SPRAY', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_72', prodotto: 'ADD GUTTIAU', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_73', prodotto: 'ADD CRUMBLE SBRISOLONA', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_74', prodotto: 'ADD SCAGLIETTE CIOCK', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_75', prodotto: 'ADD SOVRACOSCIA 125G', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_76', prodotto: 'ADD EXTRA P. PORK 100 GR', pvMedio: 3, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_81', prodotto: 'ADD SCAMONE 100G', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_82', prodotto: 'ADD TARTARE 100G', pvMedio: 3.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_83', prodotto: 'ADD CREMA PISTACCHIO 50G', pvMedio: 1.6, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_86', prodotto: 'ADD GRANA CROCCANTE 20G', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_87', prodotto: 'ADD GELATO BIRRA 60G', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_89', prodotto: 'ADD EXTRA PATTY BABY', pvMedio: 2.2, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_90', prodotto: 'ADD CAMBIO NO MEAT', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_91', prodotto: 'ADD EXTRA CUBE 100G', pvMedio: 4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_92', prodotto: 'ADD EXTRA MERLUZZO', pvMedio: 3.8, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_93', prodotto: 'ADD MELANZANE GRILL', pvMedio: 0.45, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_94', prodotto: 'ADD CAROTE GRILL', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_95', prodotto: 'ADD FINOCCHI GRILL', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_96', prodotto: 'ADD CIPOLLA GRILL', pvMedio: 0.5, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_97', prodotto: 'ADD POMODORO GRILL', pvMedio: 1, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_98', prodotto: 'ADD ZUCCHINE GRILL', pvMedio: 0.45, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_FOOD_+_99', prodotto: 'ADD MORTADELLA', pvMedio: 0.85, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_PASTA_1', prodotto: 'NO TAGLIATELLE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_PASTA_2', prodotto: 'NO MEZZELUNE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_PASTA_3', prodotto: 'NO FUSILLI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_PASTA_4', prodotto: 'ADD TAGLIATELLE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_PASTA_5', prodotto: 'ADD MEZZELUNE', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_PASTA_6', prodotto: 'ADD FUSILLI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_PASTA_7', prodotto: 'ADD GNOCCHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_PASTA_8', prodotto: 'NO GNOCCHI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI FOOD -' },
  { codice: 'VARIANTI_SALSE_-_29', prodotto: 'NO SALSA CHEDDAR', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_SALSE_-_30', prodotto: 'NO CREMA PECORINO', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_SALSE_-_31', prodotto: 'NO MOUSSE BELLA LODI', pvMedio: 0, ub: 'pz', categoria: 'VARIANTI SALSE -' },
  { codice: 'VARIANTI_SALSE_+_29', prodotto: 'ADD SALSA CHEDDAR', pvMedio: 1.4, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_SALSE_+_30', prodotto: 'ADD CREMA PECORINO', pvMedio: 1.4, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_SALSE_+_31', prodotto: 'ADD MOUSSE BELLA LODI', pvMedio: 1.4, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_SALSE_+_32', prodotto: 'BBQ ALLA BIRRA CIOTOLINA', pvMedio: 1.26, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_SALSE_+_33', prodotto: 'SALSA ALLA BIRRA CIOTOLINA', pvMedio: 1.4, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VARIANTI_SALSE_+_34', prodotto: 'SALSA BBQ BIANCA CIOTOLINA', pvMedio: 1.4, ub: 'pz', categoria: 'VARIANTI FOOD +' },
  { codice: 'VARIANTI_SALSE_+_35', prodotto: 'SALSA CHEDDAR CIOTOLINA', pvMedio: 2.8, ub: 'pz', categoria: 'VARIANTI SALSE +' },
  { codice: 'VINI_1', prodotto: 'CANNONAU BOTTIGLIA', pvMedio: 0, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_10', prodotto: 'CALICE PROSECCO', pvMedio: 5, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_12', prodotto: 'CALICE PROSECCO FESTE', pvMedio: 0, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_13', prodotto: 'TRAMINER BOTTIGLIA', pvMedio: 24, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_14', prodotto: 'CALICE TRAMINER', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_15', prodotto: 'IS VERMENTINO CALICE', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_16', prodotto: 'IS VERMENTINO BOTTIGLIA', pvMedio: 26, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_17', prodotto: 'LAMBRUSCO CALICE', pvMedio: 5, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_18', prodotto: 'LAMBRUSCO BOTTIGLIA', pvMedio: 26, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_19', prodotto: 'CALICE GALLUCCIO', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_2', prodotto: 'CALICE CANNONAU', pvMedio: 5, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_20', prodotto: 'GALLUCCIO BOTTIGLIA', pvMedio: 22, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_3', prodotto: 'DOLCETTO BOTTIGLIA', pvMedio: 22, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_4', prodotto: 'CALICE DOLCETTO', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_5', prodotto: 'VERMENTINO BOTTIGLIA', pvMedio: 22, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_6', prodotto: 'CALICE VERMENTINO', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_7', prodotto: 'ROSATO BOTTIGLIA', pvMedio: 24, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_8', prodotto: 'CALICE ROSATO', pvMedio: 6, ub: 'pz', categoria: 'VINI' },
  { codice: 'VINI_9', prodotto: 'PROSECCO PREMIUM BOTTIGLIA', pvMedio: 24, ub: 'pz', categoria: 'VINI' }
]
