-- Aggiunge gli ingredienti/varianti dall'immagine VARIANTI FOOD AND BEVERAGE
-- cost_per_unit = 0 (da inserire manualmente)
-- ON CONFLICT DO NOTHING evita duplicati se già esistono

INSERT INTO ingredients (name, unit, cost_per_unit) VALUES
  ('Senza Schiumpa', 'pz', 0),
  ('Salsa Cheddar Cotolina', 'pz', 0),
  ('Salsa BBQ Bianca Cotolina', 'pz', 0),
  ('Alla alla Bianca Cotolina', 'pz', 0),
  ('Rotritto', 'pz', 0),
  ('Poca Schiumpa', 'pz', 0),
  ('No Zucchine Grill', 'pz', 0),
  ('No Zucchine Chips', 'pz', 0),
  ('No Zucchine', 'pz', 0),
  ('No Uovo', 'pz', 0),
  ('No Tagliatelle', 'pz', 0),
  ('No Stracciatella', 'pz', 0),
  ('No Spicchio', 'pz', 0),
  ('No Soy Sauce', 'pz', 0),
  ('No Salsa Cheddar', 'pz', 0),
  ('No Salsa Carbonara', 'pz', 0),
  ('No Salsa BBQ Bianca', 'pz', 0),
  ('No Salsa Alle Erbe', 'pz', 0),
  ('No Salsa Alla Birra', 'pz', 0),
  ('No Salsa Al Peperoncino', 'pz', 0),
  ('No Rucola', 'pz', 0),
  ('No Provola Dolce', 'pz', 0),
  ('No Provola', 'pz', 0),
  ('No Prov. Dolce', 'pz', 0),
  ('No Porro Rondelle Grill', 'pz', 0),
  ('No Porro Ramato', 'pz', 0),
  ('No Poro Piccadilly', 'pz', 0),
  ('No Porro Grill', 'pz', 0),
  ('No Pesto', 'pz', 0),
  ('No Pecorino', 'pz', 0),
  ('No Patty Tartare', 'pz', 0),
  ('No Patty Manzo', 'pz', 0),
  ('No Panna Spray', 'pz', 0),
  ('No Pane', 'pz', 0),
  ('No Pancetta', 'pz', 0),
  ('No Olive', 'pz', 0),
  ('No Nutella', 'pz', 0),
  ('No Nduja', 'pz', 0),
  ('No Mozzarella Filone (100 GR)', 'pz', 0),
  ('No Mozzarella', 'pz', 0),
  ('No Mousse Bella Lodi', 'pz', 0),
  ('No Mortadella', 'pz', 0),
  ('No Mezzellune', 'pz', 0),
  ('No Melanzane Grill', 'pz', 0),
  ('No Melanzane', 'pz', 0),
  ('No Mayo Birra', 'pz', 0),
  ('No Mayo', 'pz', 0),
  ('No Marmellata Bacon e Cipolla', 'pz', 0),
  ('No Insalata', 'pz', 0),
  ('No Ins. Gentile', 'pz', 0),
  ('No Guttiau', 'pz', 0),
  ('No Grattugiato', 'pz', 0),
  ('No Grana Croccante', 'pz', 0),
  ('No Gnocchi', 'pz', 0),
  ('No Fungo', 'pz', 0),
  ('No Fungo 60 GR', 'pz', 0),
  ('No Funghi Misti', 'pz', 0),
  ('No Funghi', 'pz', 0),
  ('No Frutti di Bosco', 'pz', 0),
  ('No Fritte', 'pz', 0),
  ('No Focaccia Julienne', 'pz', 0),
  ('No Finocchi Grill', 'pz', 0),
  ('No Feta', 'pz', 0),
  ('No Fagiolini', 'pz', 0),
  ('No Emulsione Basilico', 'pz', 0),
  ('No Emulsione Basilico', 'pz', 0),
  ('No Crumble S Brisolona', 'pz', 0),
  ('No Crosta', 'pz', 0),
  ('No Crema Pistacchio', 'pz', 0),
  ('No Crema Pecorino', 'pz', 0),
  ('No Crema di Grana', 'pz', 0),
  ('No Cotoletta', 'pz', 0),
  ('No Costine 150 GR', 'pz', 0),
  ('No Controfiletto 100 GR', 'pz', 0),
  ('No Cipolla Grill', 'pz', 0),
  ('No Cipolla Fresca', 'pz', 0),
  ('No Cetriolo', 'pz', 0),
  ('No Carote Julienne', 'pz', 0),
  ('No Carote Grill', 'pz', 0),
  ('No Carote', 'pz', 0),
  ('No Burrata', 'pz', 0),
  ('No Broccoletti No Meat', 'pz', 0),
  ('No BBQ Alla Birra', 'pz', 0),
  ('No Basilico', 'pz', 0),
  ('No Bacon a Fette', 'pz', 0),
  ('No Acqua', 'pz', 0),
  ('Extra Patty Smash', 'pz', 0),
  ('No Emulsione Basilico Cremonini', 'pz', 0),
  ('BBQ Alla Birra Cotolina', 'pz', 0),
  ('Add Zucchine Grill', 'pz', 0),
  ('Add Zucchine Chips', 'pz', 0),
  ('Add Zucchine', 'pz', 0),
  ('Add Uovo', 'pz', 0),
  ('Add Verdure Grigliate', 'pz', 0),
  ('Add Uovo', 'pz', 0),
  ('Add Tartare 100G', 'pz', 0),
  ('Add Tagliatelle', 'pz', 0),
  ('Add Stracciatella', 'pz', 0),
  ('Add Spicchio', 'pz', 0),
  ('Add Sovrascoscia 150G', 'pz', 0),
  ('Add Soy Sauce', 'pz', 0),
  ('Add Scamone 100G', 'pz', 0),
  ('Add Salsa Alle Erbe', 'pz', 0),
  ('Add Salsa Cheddar', 'pz', 0),
  ('Add Salsa BBQ Bianca', 'pz', 0),
  ('Add Salsa Alla Birra', 'pz', 0),
  ('Add Salsa Alla Birra', 'pz', 0),
  ('Add Salsa Carbonara', 'pz', 0),
  ('Add Salsa Al Peperoncino', 'pz', 0),
  ('Add Rucola', 'pz', 0),
  ('Add Provola', 'pz', 0),
  ('Add Porro Ramato', 'pz', 0),
  ('Add Porro Grill', 'pz', 0),
  ('Add Pomo Ramato', 'pz', 0),
  ('Add Pomo Piccadilly', 'pz', 0),
  ('Add Petto di Pollo (120G)', 'pz', 0),
  ('Add Pepe', 'pz', 0),
  ('Add Pecorino', 'pz', 0),
  ('Add Panna Spray', 'pz', 0),
  ('Add Pane Sala', 'pz', 0),
  ('Add Pancetta', 'pz', 0),
  ('Add Vodka', 'pz', 0),
  ('Add Nutella', 'pz', 0),
  ('Add Mozzarella Filone (100 GR)', 'pz', 0),
  ('Add Mousse Bella Lodi', 'pz', 0),
  ('Add Mezzellune', 'pz', 0),
  ('Add Melanzane', 'pz', 0),
  ('Add Mayo Pomodori', 'pz', 0),
  ('Add Mayo Birra', 'pz', 0),
  ('Add Mayo', 'pz', 0),
  ('Add Marmellata Bacon e Cipolla', 'pz', 0),
  ('Add Ins. Gentile', 'pz', 0),
  ('Add Insalata', 'pz', 0),
  ('Add Guttiau', 'pz', 0),
  ('Add Grattugiato', 'pz', 0),
  ('Add Grana Croccante 20G', 'pz', 0),
  ('Add Gnocchi', 'pz', 0),
  ('Add Gelato Birra 60G', 'pz', 0),
  ('Add Fusilli', 'pz', 0),
  ('Add Fungo 60 GR', 'pz', 0),
  ('Add Funghi', 'pz', 0),
  ('Add Frutti di Bosco', 'pz', 0),
  ('Add Focaccia Julienne', 'pz', 0),
  ('Add Finocchi Grill', 'pz', 0),
  ('Add Feta', 'pz', 0),
  ('Add Fagiolini', 'pz', 0),
  ('Add Fagioli Calabria 1 PZ', 'pz', 0),
  ('Add Extra Prov. Dolce', 'pz', 0),
  ('Add Extra Petto di Pollo (120G)', 'pz', 0),
  ('Add Extra Patty Manzo', 'pz', 0),
  ('Add Extra Patty Baby', 'pz', 0),
  ('Add Extra Pancetta', 'pz', 0),
  ('Add Extra Pork 100GR', 'pz', 0),
  ('Add Extra Perluzzo', 'pz', 0),
  ('Add Extra Cure 150G', 'pz', 0),
  ('Add Extra Cotoletta 1 PZ', 'pz', 0),
  ('Add Extra Controfiletto 100 GR', 'pz', 0),
  ('Add Extra Burger No Meat', 'pz', 0),
  ('Add Emulsione Al Pesto', 'pz', 0),
  ('Add Emulsione Basilico (16)', 'pz', 0),
  ('Add Crumble S Brisolona', 'pz', 0),
  ('Add Crema Pistacchio 50G', 'pz', 0),
  ('Add Crema Pecorino', 'pz', 0),
  ('Add Costine 150G', 'pz', 0),
  ('Add Cavolo Rosso', 'pz', 0),
  ('Add Carote Julienne', 'pz', 0),
  ('Add Cipolla Grill', 'pz', 0),
  ('Add Cambio No Meat', 'pz', 0),
  ('Add Burrata', 'pz', 0),
  ('Add Broccoletti Al Pesto', 'pz', 0),
  ('Add Birra Alla Birra', 'pz', 0),
  ('Add Basilico', 'pz', 0),
  ('Add Bacon a Fette', 'pz', 0),
  ('Add Tanqueray', 'pz', 0),
  ('Add Sambuca', 'pz', 0),
  ('Add Amaro Frato Freddo', 'pz', 0),
  ('Add Macchiato Caldo', 'pz', 0),
  ('Add Limone', 'pz', 0),
  ('Add Line', 'pz', 0),
  ('Add GinAmarena Fabbri', 'pz', 0),
  ('Add Cacao', 'pz', 0),
  ('Add Cacao Fatte', 'pz', 0),
  ('Add Amaro Frato', 'pz', 0),
  ('Add Arancia', 'pz', 0),
  ('Add Birra (0.2)', 'pz', 0),
  ('Add Birra (0.4)', 'pz', 0)
ON CONFLICT (name) DO NOTHING;
