-- Importa le descrizioni piatti dal database ufficiale del menu (menu_database.json)
-- nei 27 piatti del catalogo che corrispondono per nome. Aggiorna solo catalog_items.notes,
-- non tocca prezzo/categoria/altre righe. Generato confrontando il catalogo esistente col
-- database piatti fornito dallo studio.

UPDATE catalog_items SET notes = '250 g di tagliata di sovracoscia di pollo marinato con erbe mediterranee, su foglie di rucola, servita con salsa alle erbe' WHERE id = 'db44d96d-a994-4e6c-b945-f5648209fa83'; -- Tagliata di Pollo (Brace)
UPDATE catalog_items SET notes = '250 g di tagliata di sovracoscia di pollo marinato con erbe mediterranee, bacon croccante e salsa BBQ bianca su foglie di rucola' WHERE id = '644ac5e5-4f6a-422c-91a4-e4bc4270881b'; -- Tagliata di Pollo BBQ (Brace)
UPDATE catalog_items SET notes = 'Tris di tagliata di pollo, tagliata di pollo BBQ e cotoletta di pollo con salsa miele e zenzero su foglie di rucola' WHERE id = '417ed730-1d0c-48ae-b20c-d1bac6889078'; -- Tre di Pollo (Brace)
UPDATE catalog_items SET notes = '300 g di bistecca di cuberoll di manzo su foglie di rucola, servita tagliata e rifinita con fiocchi di sale Maldon' WHERE id = '2d3b5e39-fc8d-41e7-a8c9-5c8b8bc179de'; -- La Gigante (Brace)
UPDATE catalog_items SET notes = 'Costine di maiale marinate con erbe mediterranee, su foglie di rucola e rifinite con salsa BBQ alla birra' WHERE id = '21e3d882-d4cb-4061-8924-ca521dd19925'; -- Costine di Maiale (Brace)
UPDATE catalog_items SET notes = 'Tagliata di scamone di manzo, su foglie di rucola, rifinita con fiocchi di sale Maldon (porzione mini)' WHERE id = '655be613-26e4-4fb1-9d7e-037cf4884039'; -- Mini Gran Tagliata (Brace)
UPDATE catalog_items SET notes = 'Filetto di merluzzo fritto con pomodoro ramato, insalata gentile e salsa alla birra' WHERE id = '400ff037-89e7-4122-947a-0b030abb32c3'; -- Fish and Chips (Burger)
UPDATE catalog_items SET notes = 'Insalata verde, rucola, cavolo cappuccio, pomodori ramati, carote, cetrioli, finocchi e crostini di pane fritti, con salsa alle erbe e sfoglie di pane Guttiau' WHERE id = '79528d6b-7d80-4926-b5a2-6036c4945b50'; -- Orto Fresco (Contorni)
UPDATE catalog_items SET notes = 'Mini cialda croccante aromatizzata alla cannella, farcita con crema di ricotta, granella di pistacchio e scaglie di cioccolato fondente' WHERE id = 'fe1c6649-c8bf-4734-8919-ba35de5569e3'; -- Cannolo Singolo (Dessert)
UPDATE catalog_items SET notes = 'Torta con cacao e mandorle, servita con gelato al fior di latte e zucchero a velo' WHERE id = '10260b87-c5ba-478b-bb5e-c563496bee56'; -- Torta Caprese (Dessert)
UPDATE catalog_items SET notes = 'Cialda croccante aromatizzata alla cannella, mousse di ricotta, granella di pistacchio, scaglie di cioccolato fondente e zucchero a velo' WHERE id = '569e701f-455a-459a-bd3f-c62d70c3781a'; -- Cannolo Scomposto (Dessert)
UPDATE catalog_items SET notes = 'Insalata verde, cavolo cappuccio rosso, tagliata di scamone di manzo, burrata, pomodori ramati, rucola e crostini di pane fritti, con salsa alle erbe e sfoglie di pane Guttiau' WHERE id = '96d8f4d6-5db4-47f1-8fc7-efae5c0937a5'; -- Manzo e Burrata (Insalate)
UPDATE catalog_items SET notes = 'Fusilli, pesto di pomodori secchi, olive, zucchine, carote, raspadura di Bella Lodi e foglie di basilico' WHERE id = '7fab813e-0717-4afd-9dbb-38b56f7aedb4'; -- Fusilli Pesto Rosso (Paste)
UPDATE catalog_items SET notes = 'Tagliatelle all''uovo con ragù di carne, formaggio grattugiato Bella Lodi e foglie di basilico' WHERE id = '32f76f06-f9be-4b21-b406-cbda4c5f7094'; -- Tagliatelle al Ragù (Paste)
UPDATE catalog_items SET notes = 'Pomodoro, mozzarella e basilico' WHERE id = '1e85825f-d2cb-45e0-a48b-92a1de531f47'; -- Margherita (Pizze)
UPDATE catalog_items SET notes = 'Salsa di pomodoro, ''nduja, burrata, cipolla rossa, emulsione al basilico e foglie di basilico' WHERE id = 'c34e2473-7130-4790-accb-6a27a8e269fb'; -- Burrata e 'Nduja (Pizze)
UPDATE catalog_items SET notes = 'Prosciutto crudo di Parma DOP, mozzarella, pomodori Piccadilly, Raspadura Bella Lodi e foglie di basilico' WHERE id = '7265fa35-1965-4ec6-bef0-f42d34750be7'; -- Crudo e Piccadilly (Pizze)
UPDATE catalog_items SET notes = 'Salsa di pomodoro, mozzarella, zucchine, carote, melanzane, cipolla rossa e foglie di basilico' WHERE id = '37841156-b602-4597-892c-c1b3e029a715'; -- Ortolana (Pizze)
UPDATE catalog_items SET notes = 'Anelli di cipolla pastellati con birra, serviti con maionese ai pomodori secchi' WHERE id = 'cfd1f424-12c2-40fc-9e16-fd630e8e3f6f'; -- Anelli di Cipolla (Starter)
UPDATE catalog_items SET notes = 'Mozzarelle in carrozza panate servite con maionese ai pomodori secchi' WHERE id = '26db8f6d-33e0-4589-8b74-c740d6a3ceb0'; -- MOZZARELLE IN CARROZZA (Starter)
UPDATE catalog_items SET notes = 'Burrata, pomodori ramati, olive, emulsione al basilico e foglie di basilico' WHERE id = '8d89614d-6e4c-462f-b8f1-f4f04b84f592'; -- Caprese di Burrata e Pomodori (Starter)
UPDATE catalog_items SET notes = '100 g di tartare di manzo condita con emulsione al basilico, olio e sale, servita con mousse di formaggio Bella Lodi, carote, granella di pistacchio e sfoglie di pane Guttiau' WHERE id = '70dccbe7-9e40-440c-aaf4-ed8130dedb8e'; -- Tartare Pistacchio e Bella Lodi (Starter)
UPDATE catalog_items SET notes = 'Spiedini di pollo panati serviti con limone fresco' WHERE id = '8be16b44-edab-46a6-b86a-f00ae4ff1972'; -- Spiedini di Pollo Panati (Starter)
UPDATE catalog_items SET notes = 'Rondelle di melanzane impanate servite con maionese alla birra' WHERE id = '04ab4a21-706a-44b7-9433-69aa354b5ab7'; -- Rondelle di Melanzana (Starter)
UPDATE catalog_items SET notes = 'Le nostre patate chips con marmellata di bacon e cipolla e crema di formaggio Bella Lodi' WHERE id = 'a70f29f6-941f-4f86-82e3-ca753b5408bd'; -- Chips Bella Lodi (Starter)
UPDATE catalog_items SET notes = 'Arrosticini di manzo e agnello serviti con limone fresco' WHERE id = '4e5cd8d3-5955-4934-91d0-50798b631ca4'; -- Arrosticini Abruzzesi (Starter)
UPDATE catalog_items SET notes = 'Mortadella di Bologna IGP, prosciutto crudo di Parma DOP, mousse di formaggio Bella Lodi, spicchi di focaccia al rosmarino e pasta fresca croccante fritta' WHERE id = 'e50989dd-07e0-4d63-864a-164543ace8fc'; -- Antipasto Tricolore (Starter)
